const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8767/',{waitUntil:'networkidle'});
 await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:'/private/tmp/fern-check/desktop.png'});
 assert.equal(await page.locator('.card').count(),24);
 await page.locator('.card').first().click();
 await page.waitForTimeout(650);
 assert.equal(await page.locator('#detail').evaluate(e=>e.open),true);
 await page.screenshot({path:'/private/tmp/fern-check/detail.png'});
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#detail').evaluate(e=>e.open),false);
 assert.equal(await page.locator('.card').first().evaluate(e=>e===document.activeElement),true);
 await page.locator('#search').fill('Christmas');
 assert.equal(await page.locator('.card').count(),1);
 await page.locator('#search').fill('');
 await page.locator('#more').click();assert.equal(await page.locator('.card').count(),48);
 await page.locator('#wind').click();assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('still')),true);
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'/private/tmp/fern-check/mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No mobile horizontal overflow');
 await page.locator('.card').first().click();await page.waitForTimeout(650);await page.screenshot({path:'/private/tmp/fern-check/mobile-detail.png'});await page.keyboard.press('Escape');
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('.frond').first().evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: desktop/mobile rendering, card dialog, Escape, focus restoration, search, pagination, wind, reduced motion, no mobile overflow, no JavaScript errors.');
})().catch(e=>{console.error(e);process.exit(1)});
